[package]
name = "rust-tracer"
version = "0.1.0"
authors = ["Marc DellaVolpe <marc@cureatr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = {}
nalgebra = {}
threadpool = {}
rand = {}